name: Build Super Secret Group APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Buildozer and dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libtinfo5
        pip3 install buildozer cython virtualenv
        
    - name: Build APK with Buildozer
      run: |
        buildozer android debug
        echo "✅ APK собран успешно!"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: super-secret-group
        path: bin/*.apk
