name: Build MrAnatas9 App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download APK
      run: wget -O MrAnatas9-app.apk "https://github.com/simplex-chat/simplex-chat/releases/latest/download/simplex-aarch64.apk"
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MrAnatas9-app
        path: MrAnatas9-app.apk
