name: Build MrAnatas9 App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Android
      uses: android-actions/setup-android@v2
      with:
        licenses: true

    - name: Install Python and Buildozer
      run: |
        pip3 install buildozer kivy cython

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mr-anatas9-app
        path: bin/*.apk
