name: Build MrAnatas9 REAL App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java and Android
      uses: android-actions/setup-android@v2
      
    - name: Accept Android licenses
      run: |
        yes | sdkmanager --licenses
        sdkmanager "build-tools;34.0.0" "platforms;android-33"
        
    - name: Install Python and Buildozer
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-venv
        pip3 install buildozer kivy cython
        
    - name: Build REAL MrAnatas9 APK
      run: |
        buildozer android debug
        echo "✅ НАСТОЯЩЕЕ приложение MrAnatas9 собрано!"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mr-anatas9-REAL-app
        path: bin/*.apk
