name: Build MrAnatas9 Real App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create custom APK structure
      run: |
        # Создаем базовую структуру APK
        mkdir -p app_build/res/values
        mkdir -p app_build/META-INF
        
        # Файл с названием приложения
        echo '<?xml version="1.0" encoding="utf-8"?>
        <resources>
            <string name="app_name">MrAnatas9 Secret Group</string>
        </resources>' > app_build/res/values/strings.xml
        
        # Манифест приложения
        echo '<?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android"
            package="org.mranatas9.secretgroup">
            <application android:label="MrAnatas9 App">
            </application>
        </manifest>' > app_build/AndroidManifest.xml
        
        # Создаем APK
        cd app_build
        zip -r ../mr-anatas9-real-app.apk .
        echo "✅ Кастомный APK создан!"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mr-anatas9-real-app
        path: mr-anatas9-real-app.apk
