name: Build MrAnatas9 Real App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Buildozer dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip autoconf automake libtool pkg-config zip unzip
        pip3 install buildozer cython
    
    - name: Build Android APK
      run: |
        buildozer init
        buildozer android debug
        
    - name: Upload Real APK
      uses: actions/upload-artifact@v4
      with:
        name: mr-anatas9-real-app
        path: bin/*.apk
