name: Build MrAnatas9 App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Force Android SDK setup
      run: |
        sudo apt update
        sudo apt install -y wget unzip openjdk-11-jdk
        
        # Скачиваем SDK
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk/cmdline-tools/latest
        mv cmdline-tools/* android-sdk/cmdline-tools/latest/
        
        export ANDROID_HOME=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        
        # ПРИНУДИТЕЛЬНОЕ ПРИНЯТИЕ ЛИЦЕНЗИЙ
        mkdir -p $ANDROID_HOME/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
        
        # Устанавливаем пакеты (лицензии уже приняты)
        sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-33"

    - name: Install Python and Buildozer
      run: |
        pip3 install buildozer kivy cython

    - name: Build APK
      run: |
        export ANDROID_HOME=$PWD/android-sdk
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mr-anatas9-app
        path: bin/*.apk
