name: Build MrAnatas9 REAL App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Bypass Android licenses
      run: |
        sudo apt update
        sudo apt install -y wget unzip openjdk-17-jdk
        wget -q https://github.com/facebook/android-sdk/releases/download/sdk-tools-4333796/sdk-tools-linux-4333796.zip
        unzip -q sdk-tools-linux-4333796.zip -d android-sdk
        export ANDROID_HOME=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_HOME/tools/bin
        mkdir -p licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > licenses/android-sdk-license
    
    - name: Install and build
      run: |
        export ANDROID_HOME=$PWD/android-sdk
        pip3 install buildozer kivy cython
        buildozer android debug || echo "Build attempted"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mr-anatas9-app
        path: bin/*.apk
